/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula;

import javax.swing.JOptionPane;

/**
 *
 * @author ricardo_s_netto
 */
public class janela extends javax.swing.JFrame {

    public static void escolha() {
        int n = Integer.parseInt(JOptionPane.showInputDialog("Digite 1 para calculadora de media\nDigite 2 para calculadora de formula de bhaskara\nDigite 3 para manipular strings\nDigite 0 para sair"));
        if (n == 1) {
            calcMedia();
        } else if (n == 2) {
            calcformuladebhaskara();
        } else if (n == 3) {
            manipulaString();
        } else if (n == 0) {
            JOptionPane.showMessageDialog(null, "Volte sempre!");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma opção valida");
            zoeiras();
        }
    }

    public static void calcMedia() {
        int qtd = Integer.parseInt(JOptionPane.showInputDialog("Digite a quantidade de numeros que deseja calcular a média."));
        float soma = 0;
        for (int i = 1; i <= qtd; i++) {
            soma = soma + Integer.parseInt(JOptionPane.showInputDialog("digite o " + i + " numero!"));
        }
        float media = soma / qtd;
        JOptionPane.showMessageDialog(null, soma);

    }

    public static void calcformuladebhaskara() {
        int a = Integer.parseInt(JOptionPane.showInputDialog("digite o valor de a."));
        int b = Integer.parseInt(JOptionPane.showInputDialog("digite o valor de b."));
        int c = Integer.parseInt(JOptionPane.showInputDialog("digite o valor de c."));
        double delta = b * b - 4 * a * c;
        double x1 = (-b + Math.sqrt(delta)) / 2 * a;
        double x2 = (-b - Math.sqrt(delta)) / 2 * a;
        JOptionPane.showMessageDialog(null, "resposta: " + x1);
        JOptionPane.showMessageDialog(null, "resposta: " + x2);

    }

    public static void manipulaString() {
        int num = Integer.parseInt(JOptionPane.showInputDialog("Digite um numero inteiro"));
        String mensagem = "o numero digitado é ";
        if (num < 0) {
            mensagem += "positivo";
        } else if (num > 0) {
            mensagem += "negativo";
        } else {
            mensagem += "neutro";
        }
        if (num % 2 == 0) {
            mensagem += " e par";
        } else {
            mensagem += " e ímpar";
        }
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public static void zoeiras() {
        String sacanagem = "oi";
        for (int i = 1; i < 2; i--) {
            sacanagem += JOptionPane.showInputDialog(sacanagem);
            if (sacanagem.contains("palmeiras não tem mundial")) {
                i = 3;
            }
        }
        JOptionPane.showMessageDialog(null, "isso mesmo!");
        escolha();

    }

   /**
     * Creates new form janela
     */
    public janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoescolha = new javax.swing.JButton();
        numerospares = new javax.swing.JButton();
        numerosprimos = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menutela2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoescolha.setText("Escolha");
        botaoescolha.setBorder(new javax.swing.border.MatteBorder(null));
        botaoescolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoescolhaActionPerformed(evt);
            }
        });
        jPanel1.add(botaoescolha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 70, 20));

        numerospares.setText("Pares");
        numerospares.setActionCommand("pares");
        numerospares.setBorder(new javax.swing.border.MatteBorder(null));
        numerospares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosparesActionPerformed(evt);
            }
        });
        jPanel1.add(numerospares, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 60, 20));

        numerosprimos.setText("Primos");
        numerosprimos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numerosprimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosprimosActionPerformed(evt);
            }
        });
        jPanel1.add(numerosprimos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 70, 20));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N
        jPanel1.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Arquivo");

        menutela2.setText("Tela2");
        menutela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutela2ActionPerformed(evt);
            }
        });
        jMenu1.add(menutela2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoescolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoescolhaActionPerformed
        escolha();
    }//GEN-LAST:event_botaoescolhaActionPerformed

    private void menutela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutela2ActionPerformed
        tela2.abrir();
        dispose();
    }//GEN-LAST:event_menutela2ActionPerformed

    private void numerosparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosparesActionPerformed
        int digito = Integer.parseInt(JOptionPane.showInputDialog(this, "digite um numero inteiro positivo"));
        String resultado = "Os numeros pares de 0 até " + digito + " são\n";
        for (int i = 0; i <= digito; i++) {
            if (i % 2 == 0) {
                resultado += "\n" + i;
            }
        }
        JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_numerosparesActionPerformed

    private void numerosprimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosprimosActionPerformed

        int numero = Integer.parseInt(JOptionPane.showInputDialog(this, "digite o numero"));
        String resultado = "numeros primos";

        for (int i = 1; i <= numero; i++) {
            int divisores = 0;
            for (int j = 1; j <= i; j++) {
                if (i % j == 0) {
                    divisores++;
                }
            }
            if (divisores == 2) {
                resultado += "\nO numero " + i + " é primo!";
            }
        }
        JOptionPane.showMessageDialog(this, resultado);
    }//GEN-LAST:event_numerosprimosActionPerformed

    public static void abrir() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela().setVisible(true);
            }
        });
    }
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoescolha;
    private javax.swing.JLabel fundo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menutela2;
    private javax.swing.JButton numerospares;
    private javax.swing.JButton numerosprimos;
    // End of variables declaration//GEN-END:variables
}
