/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula;

/**
 *
 * @author ricardo_s_netto
 */
public class tela2 extends javax.swing.JFrame {

    /**
     * Creates new form tela2
     */
    public tela2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        campohorainicial = new javax.swing.JTextField();
        campominutoinicial = new javax.swing.JTextField();
        campohorafinal = new javax.swing.JTextField();
        campominutofinal = new javax.swing.JTextField();
        labelresultadohora = new javax.swing.JLabel();
        labelresutadominuto = new javax.swing.JLabel();
        labelhorainicial = new javax.swing.JLabel();
        labelhorafinal = new javax.swing.JLabel();
        labelminutoinicial = new javax.swing.JLabel();
        labelminutofinal = new javax.swing.JLabel();
        botaosomar = new javax.swing.JButton();
        botaosubtrair = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Tela1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel.setBackground(new java.awt.Color(0, 255, 102));

        campohorainicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campohorainicialActionPerformed(evt);
            }
        });

        campohorafinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campohorafinalActionPerformed(evt);
            }
        });

        labelhorainicial.setText("Hora inicial:");

        labelhorafinal.setText("Hora final:");

        labelminutoinicial.setText("Minuto inicial:");

        labelminutofinal.setText("Minuto final:");

        botaosomar.setText("somar");
        botaosomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosomarActionPerformed(evt);
            }
        });

        botaosubtrair.setText("subtrair");
        botaosubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosubtrairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaosomar)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelhorainicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelhorafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelresultadohora))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campohorainicial, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(campohorafinal))))))
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(botaosubtrair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelminutoinicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelminutofinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelresutadominuto)
                            .addComponent(campominutoinicial, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(campominutofinal))))
                .addGap(53, 53, 53))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campohorainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campominutoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelhorainicial)
                    .addComponent(labelminutoinicial))
                .addGap(57, 57, 57)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campohorafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campominutofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelhorafinal)
                    .addComponent(labelminutofinal))
                .addGap(32, 32, 32)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelresultadohora)
                    .addComponent(labelresutadominuto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaosomar)
                    .addComponent(botaosubtrair))
                .addGap(27, 27, 27))
        );

        jMenu2.setText("Telas");

        Tela1.setText("Tela1");
        Tela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tela1ActionPerformed(evt);
            }
        });
        jMenu2.add(Tela1);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tela1ActionPerformed
        janela.abrir();        // TODO add your handling code here:
    }//GEN-LAST:event_Tela1ActionPerformed

    private void campohorainicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campohorainicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campohorainicialActionPerformed

    private void botaosomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosomarActionPerformed
        int horainicial = Integer.parseInt(campohorainicial.getText());
        int horafinal = Integer.parseInt(campohorafinal.getText());
        int minutoinicial = Integer.parseInt(campominutoinicial.getText());
        int minutofinal = Integer.parseInt(campominutofinal.getText());

        int resultadohora = horainicial + horafinal;
        int resultadominuto = minutoinicial + minutofinal;

        while (resultadominuto > 59) {
            resultadominuto -= 60;
            resultadohora++;
        }

        labelresultadohora.setText(resultadohora + " horas");
        labelresutadominuto.setText(resultadominuto + " minutos");
    }//GEN-LAST:event_botaosomarActionPerformed

    private void campohorafinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campohorafinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campohorafinalActionPerformed

    private void botaosubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosubtrairActionPerformed
        int horainicial = Integer.parseInt(campohorainicial.getText());
        int horafinal = Integer.parseInt(campohorafinal.getText());
        int minutoinicial = Integer.parseInt(campominutoinicial.getText());
        int minutofinal = Integer.parseInt(campominutofinal.getText());

        while(minutoinicial > 59);{
            horainicial++;
            minutoinicial -= 60;
    }
        while(minutofinal > 59);{
            horafinal++;
            minutofinal -= 60;
    }
        int resultadohora = horainicial - horafinal;
        int resultadominuto = minutoinicial - minutofinal;
        if(resultadohora == 0){
            if(minutoinicial < minutofinal){
                resultadominuto = minutofinal - minutoinicial;
            }
                }
        while (resultadominuto > 59) {
            resultadominuto -= 60;
            resultadohora++;       
    }//GEN-LAST:event_botaosubtrairActionPerformed
        if(horainicial < horafinal){
            resultadohora = horafinal - horainicial;
            resultadominuto = minutofinal - minutoinicial;
        }
        while(resultadominuto < 0);{
            resultadohora --;
            resultadominuto += 60;
    }
        
        labelresultadohora.setText(resultadohora + " horas");
        labelresutadominuto.setText(resultadominuto + " minutos");
    }

    /**
     * @param args the command line arguments
     */
    public static void abrir() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Tela1;
    private javax.swing.JButton botaosomar;
    private javax.swing.JButton botaosubtrair;
    private javax.swing.JTextField campohorafinal;
    private javax.swing.JTextField campohorainicial;
    private javax.swing.JTextField campominutofinal;
    private javax.swing.JTextField campominutoinicial;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel labelhorafinal;
    private javax.swing.JLabel labelhorainicial;
    private javax.swing.JLabel labelminutofinal;
    private javax.swing.JLabel labelminutoinicial;
    private javax.swing.JLabel labelresultadohora;
    private javax.swing.JLabel labelresutadominuto;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
